---
name: Daily Tests - mkosi (x64)

on:  # yamllint disable-line rule:truthy
    schedule:
        - cron: '30 23 * * *'   # every day at 23:30 UTC

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    pull_request:
        paths:
            - '.github/workflows/daily-mkosi-x64.yml'

jobs:
    mkosi:
        name: ${{ matrix.config.test }} on ${{ matrix.container }} with mkosi
        runs-on: ubuntu-24.04
        timeout-minutes: 30
        concurrency:
            group: >
                daily-mkosi-${{ github.workflow }}-${{ github.ref }}
                -${{ matrix.container }}-${{ matrix.config.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container:
                    - opensuse:latest
                config:
                    - {test: '41', deps: 'mkosi-initrd'}
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}
            options: '--device=/dev/kvm --privileged'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v6
            - name: "TEST-${{ matrix.config.test }}"
              run: >
                TEST_CONTAINER_COMMAND="zypper --non-interactive install ${{ matrix.config.deps }}"
                ./test/test-container.sh "TEST-${{ matrix.config.test }}" ${{ matrix.config.test }}
