---
name: Daily Tests - systemd-networkd

on:  # yamllint disable-line rule:truthy
    schedule:
        - cron: '30 23 * * *'   # every day at 23:30 UTC

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    pull_request:
        paths:
            - '.github/workflows/daily-systemd-networkd.yml'

jobs:
    systemd-networkd:
        name: >
            ${{ matrix.test }} on ${{ matrix.container }}
            ${{ matrix.network }} networking on ${{ matrix.architecture.tag }}
        runs-on: ${{ matrix.architecture.runner }}
        timeout-minutes: 40
        concurrency:
            group: >
                daily-systemd-networkd-${{ github.workflow }}-${{ github.ref }}
                -${{ matrix.container }}-${{ matrix.test }}
                -${{ matrix.network }}-${{ matrix.architecture.tag }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                architecture:
                    - {runner: 'ubuntu-24.04', tag: 'amd'}
                    - {runner: 'ubuntu-24.04-arm', tag: 'arm'}
                network:
                    - systemd-networkd
                container:
                    - arch:latest
                    - ubuntu:devel
                    - ubuntu:rolling
                test:
                    - "50"
                exclude:
                    - container: arch:latest
                      architecture: {runner: 'ubuntu-24.04-arm', tag: 'arm'}
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}
            options: '--device=/dev/kvm --privileged'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v6
            - name: "${{ matrix.container }} TEST-${{ matrix.test }}"
              run: >
                USE_NETWORK=${{ matrix.network }}
                ./test/test-container.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
