---
name: Daily Integration Tests (arm64)

on:  # yamllint disable-line rule:truthy
    schedule:
        - cron: '30 23 * * *'   # every day at 23:30 UTC

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    pull_request:
        paths:
            - '.github/workflows/integration-extra-arm64.yml'

jobs:
    arm64:
        name: ${{ matrix.test }} on ${{ matrix.container }} on arm64
        runs-on: ubuntu-24.04-arm
        timeout-minutes: 20
        concurrency:
            group: extra-arm64-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container:
                    - debian:latest
                    - gentoo:latest
                    - opensuse:latest
                    - ubuntu:devel
                    - ubuntu:rolling
                    - void:latest
                test:
                    - "10"
                    - "11"
                    - "13"
                    - "20"
                    - "26"
                    - "30"
                    - "50"
                    - "80"
                    - "81"
                    - "82"
                exclude:
                    # run-qemu: Could not find a Linux kernel version to test with!
                    - container: void:latest
                      test: "82"
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}-arm
            options: '--privileged'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v6
            - name: "${{ matrix.container }} TEST-${{ matrix.test }}"
              run: ./test/test-container.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    systemd-arm64:
        name: ${{ matrix.test }} on ${{ matrix.container }} on arm64
        runs-on: ubuntu-24.04-arm
        timeout-minutes: 20
        concurrency:
            group: extra-systemd-arm64-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container:
                    - debian:latest
                    - gentoo:latest
                    - opensuse:latest
                    - ubuntu:devel
                    - ubuntu:rolling
                test:
                    - "40"
                    - "41"
                    - "42"
                    - "43"
                    - "44"
                exclude:
                    # mkosi test step fails
                    - container: opensuse:latest
                      test: "41"
                    # fails with key file '/run/credentials/@system/key' missing
                    - container: gentoo:latest
                      test: "41"
                    # /boot/vmlinuz-... is missing .efi suffix: https://launchpad.net/bugs/2133402
                    - container: ubuntu:devel
                      test: "43"
                    # /boot/vmlinuz-... is missing .efi suffix: https://launchpad.net/bugs/2133402
                    - container: ubuntu:rolling
                      test: "43"
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}-arm
            options: '--privileged'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v6
            - name: "${{ matrix.container }} TEST-${{ matrix.test }}"
              run: ./test/test-container.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
