name: Commisery
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  commit-message:
    name: Conventional Commit Message Checker (Commisery)
    runs-on: ubuntu-latest
    steps:
    - name: Check-out the repo under $GITHUB_WORKSPACE
      uses: actions/checkout@v3

    - name: Run Commisery
      uses: tomtom-international/commisery-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # don't validate the pull request title
        validate-pull-request: false
        validate-pull-request-title-bump: false
